### ISSUE TITLE
Beginners Guide Changes

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-Docs#17]
![image](https://user-images.githubusercontent.com/50651578/173007972-cd981fae-d339-41f0-84a9-2a686b8361ef.png)
Change to "One of the scenarios" and link to `https://steamcommunity.com/id/OfficialAntiStasiCommunity/myworkshopfiles/?appid=107410`.

![image](https://user-images.githubusercontent.com/50651578/173008073-1d3d0b3f-7724-4dc4-98f1-c706df0b605e.png)
Reverse the order from least complicated to most complicated. Basically exactly the opposite.

![image](https://user-images.githubusercontent.com/50651578/173008257-b810249d-4078-414e-9386-ac0b0bcf2404.png)
Change order (not the names) to:
- Petros
- Whiteboard
- Flag
- Tent
- Arsenal
- Garage
- Garage Sources

![image](https://user-images.githubusercontent.com/50651578/173008549-c4e2eee3-ed84-4ffb-87da-100deff83890.png)
Sort the topics in alphabetical order.
Assassination, Conquest, Convoy.....

**Comment by targetingsnake** [comment]
also sort them in [mission overview](https://official-antistasi-community.github.io/A3-Antistasi-Docs/reference_guide/missions_info/missions_overview.html) as well as in [mission info](https://official-antistasi-community.github.io/A3-Antistasi-Docs/reference_guide/missions_info/mission_info.html)?

**Comment by Bob-Murphy** [comment]
Yes, please do.
Thank you!
