### ISSUE TITLE
Antistasi short description text

### ISSUE THREAD

**Issue by Giddius** [official-antistasi-community/A3-Antistasi-Docs#2]
A short description of Antistasi in general for the start page is needed.

This can either be put in [short_description.txt](https://github.com/official-antistasi-community/A3-Antistasi-Docs/blob/main/data/short_description.txt) or directly into [index.rst](https://github.com/official-antistasi-community/A3-Antistasi-Docs/blob/main/source/index.rst) by replacing the
```rst
   .. include:: ../data/short_description.txt
```

with the text (indented once)

**Comment by Bob-Murphy** [comment]
Solved for 3.0.0 release.
I provided text, Martin merged.
