### ISSUE TITLE
Delete unused folder

### ISSUE THREAD

**Issue by targetingsnake** [official-antistasi-community/A3-Antistasi-Docs#40]
Check if Folder `docs` is unused if so, then delete folder pls

**Comment by Giddius** [comment]
The docs folder is the actual folder for the built HTML. Github requires you to put the files for the Website into a folder named `docs` located in the root-dir.

There should be no .rst in there and the only way it could be populated is if someone built the docs locally, not via using the `task` but sphinx directly and then commited it. Still I am confused. Could you explain what happened?

**Comment by targetingsnake** [comment]
@Bob-Murphy  pushed change requests by accident to `docs/_source` according to github, that repository was only written by 3 persons multiple times, which where @Giddius , @SeanDrum or the github actions.

**Comment by Giddius** [comment]
ok something happened, it should not build this, as including source is turned of in the config.
Will delete the `_source` forlder and double check if it is still turned off in the config.
