### ISSUE TITLE
CDLC Western Sahara factions & modset is missing from guide

### ISSUE THREAD

**Issue by ante185** [official-antistasi-community/A3-Antistasi-Docs#71]
at this [guide page](https://official-antistasi-community.github.io/A3-Antistasi-Docs/beginners_guide/raw_beginners_guide.html#supported-modsets-maps) the inclusion of the western sahara factions has yet to be added.

Rebel faction 
Tura

Enemy faction
ION Services
SFIA  (Sefrawi Freedom and Independence Army)
ADF  (Arganian Defence Force)
CSAT  (North African version)
NATO  (Desert camo)

Civilian faction
Western Sahara (omittable as no other guide entry features the civilian faction)

**Comment by targetingsnake** [comment]
Please attach the needed launcher preset if you want to have it linked in the guide as you mentioned in the header.  Also please poke Bob on discord if there are mods needed so he can create an Steam-Collection for those mods.
